embedding_size: [64]
feat_embed_dim: 64

n_mm_layers: 1
n_layers: 2
knn_k: [10]
mm_image_weight: 0.1
aggr_mode: ['add']
learning_rate: [0.0001]
reg_weight: [0.0001]
kl_weight: [1.0]
hyper_parameters: ["embedding_size","knn_k", "aggr_mode", "reg_weight", "learning_rate","kl_weight","c2"]
